### ISSUE TITLE
Una poronga

### ISSUE THREAD

**Issue by Mamamelchoto21** [GalaxyM4/memory-game#1]
Hola, soy alberto, tengo 21 años y vengo a criticar este juego. Me parece un mal juego, es horrible, le falta diseño y diversión, podrías ponerle a momo de fondo de pantalla por EJEMPLO, es aburrido, el creador es aburrido y tonto, no sabe programar, es un hijo de puta

**Comment by GalaxyM4** [comment]
procede a borrar la critica

**Comment by Mamamelchoto21** [comment]
Te voy a tumbar el juego hijo de puta  dame mis creditos

**Comment by GalaxyM4** [comment]
no abril

**Comment by Mamamelchoto21** [comment]
Hijo de puta horrible

**Comment by Mamamelchoto21** [comment]
Como te doy strike

**Comment by Mamamelchoto21** [comment]
**
![Uploading image.png…]()
**

**Comment by Mamamelchoto21** [comment]
@GalaxyM4 luis

**Comment by Mamamelchoto21** [comment]
Luis

**Comment by Mamamelchoto21** [comment]
#justinlovers

**Comment by Mamamelchoto21** [comment]
12345678991011121314151617181920

**Comment by Mamamelchoto21** [comment]
Maldito peruano

**Comment by Mamamelchoto21** [comment]
🤪
